use_frameworks!

platform :ios, '10.0'

target 'DRNetWork_Example' do
  pod 'DRNetWork', :path => '../'
  target 'DRNetWork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
