use_frameworks!

platform :ios, '10.0'

target 'DRNetWork_Example' do
  pod 'DRNetWork', :path => '../'
  
  pod 'AFNetworking'
  pod 'Reachability'
  
  # 提示框
  pod 'SVProgressHUD'
  pod 'MBProgressHUD'


  target 'DRNetWork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
